import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './components/Navbar'
import ParentProviders from './providers/ParentProviders'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Derrick Resume',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} dark:bg-stone-800`}>
        <ParentProviders> 
          <Navbar />
          {children}
        </ParentProviders>
        
      </body>
    </html>
  )
}
